runtime: aspnetcore
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8"

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

manual_scaling:
  instances: 1

env_variables:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://*:$PORT