runtime: aspnetcore
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "9"  # .NET 9 için güncellendi

resources:
  cpu: 1
  memory_gb: 1  # Bellek artırıldı
  disk_size_gb: 10

manual_scaling:
  instances: 1

env_variables:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://*:$PORT
  SQL_CONNECTION_STRING: "Server=94.73.151.19;Database=u7401826_hakem;User Id=u7401826_hakem;Password=zdv@4-B8j.X3:I3R;TrustServerCertificate=true;MultipleActiveResultSets=true;"
  YouTube__ApiKey: "AIzaSyBQUY--FsoJkKQNsW5q5fO9DvNhnlg9d9Q"