// <auto-generated />
using System;
using HakemYorumlari.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HakemYorumlari.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250817110814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HakemYorumlari.Models.HakemYorumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DogruKarar")
                        .HasColumnType("bit");

                    b.Property<string>("Kanal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("int");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YorumcuAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PozisyonId");

                    b.ToTable("HakemYorumlari");
                });

            modelBuilder.Entity("HakemYorumlari.Models.KullaniciAnketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DogruKarar")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OyTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PozisyonId", "KullaniciIp")
                        .IsUnique();

                    b.ToTable("KullaniciAnketleri");
                });

            modelBuilder.Entity("HakemYorumlari.Models.Mac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deplasman")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EvSahibi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Hafta")
                        .HasColumnType("int");

                    b.Property<string>("Liga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MacTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Skor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Maclar");
                });

            modelBuilder.Entity("HakemYorumlari.Models.Pozisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Dakika")
                        .HasColumnType("int");

                    b.Property<int>("MacId")
                        .HasColumnType("int");

                    b.Property<string>("PozisyonTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MacId");

                    b.ToTable("Pozisyonlar");
                });

            modelBuilder.Entity("HakemYorumlari.Models.HakemYorumu", b =>
                {
                    b.HasOne("HakemYorumlari.Models.Pozisyon", "Pozisyon")
                        .WithMany("HakemYorumlari")
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozisyon");
                });

            modelBuilder.Entity("HakemYorumlari.Models.KullaniciAnketi", b =>
                {
                    b.HasOne("HakemYorumlari.Models.Pozisyon", "Pozisyon")
                        .WithMany("KullaniciAnketleri")
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozisyon");
                });

            modelBuilder.Entity("HakemYorumlari.Models.Pozisyon", b =>
                {
                    b.HasOne("HakemYorumlari.Models.Mac", "Mac")
                        .WithMany("Pozisyonlar")
                        .HasForeignKey("MacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mac");
                });

            modelBuilder.Entity("HakemYorumlari.Models.Mac", b =>
                {
                    b.Navigation("Pozisyonlar");
                });

            modelBuilder.Entity("HakemYorumlari.Models.Pozisyon", b =>
                {
                    b.Navigation("HakemYorumlari");

                    b.Navigation("KullaniciAnketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
